spring:
  datasource:
    url: jdbc:mysql://localhost:3306/integration_test_master_data?useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw&autoReconnect=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin

  jpa:
    hibernate.ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8443
  ssl:
    key-store: classpath:certs/local-keystore.p12
    key-store-password: dummypassword
    keyStoreType: PKCS12
    key-alias: tomcat
