spring:
  datasource:
    url: jdbc:h2:mem:testdb;INIT=CREATE SCHEMA IF NOT EXISTS MOVIE\;CREATE SCHEMA IF NOT EXISTS ERROR\;CREATE SCHEMA IF NOT EXISTS AUTHENTICATION
    driver-class-name: org.h2.Driver
    username: admin
    password: admin

  jpa:
    hibernate.ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8443
  ssl:
    key-store: classpath:certs/local-keystore.p12
    key-store-password: dummypassword
    keyStoreType: PKCS12
    key-alias: tomcat
