spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev_master_data_dev?useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw&autoReconnect=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ENC(4sZS5/oGTUwJN+MWSUPDaNBIFZh6D6yzpUbd59FykJI=)
    
  jpa:
    hibernate.ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8443
  ssl:
    key-store: classpath:certs/local-keystore.p12
    key-store-password: dummypassword
    keyStoreType: PKCS12
    key-alias: tomcat
