spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev_master_data_dev?autoReconnect=true&useSSL=false
    username: root
    password: admin
    
  jpa.hibernate.ddl-auto: validate

server.port: 8443

server:
  ssl:
    key-store: classpath:certs/local-keystore.p12
    key-store-password: dummypassword
    keyStoreType: PKCS12
    key-alias: tomcat

logging:
  level:
    com.adamkorzeniak: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    
params:
  movie:
    movies:
      MIN: year,duration,rating,watchPriority
      MAX: year,duration,rating,watchPriority
      MATCH: title
      SEARCH: title,description,review,plotSummary
      EXIST: rating,watchPriority,review,plotSummary
      ORDER: title,year,duration,rating,watchPriority
    genres:
      MATCH: name
      SEARCH: name
      EXIST: name
      ORDER: name
  error:
    errors:
      SEARCH: description
    
  
