spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev_master_data_dev?autoReconnect=true&useSSL=false
    username: root
    password: admin
    
  jpa.hibernate.ddl-auto: validate

server.port: 8080

logging:
  level:
    com.adamkorzeniak: DEBUG

