spring:
  profiles:
    active: local
    include: application-${spring.profiles.active}.yml

logging:
  level:
    com.adamkorzeniak: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

api:
  yaml:
    file: file:docs/api/master-data-swagger.json
