spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
    
  jpa.hibernate.ddl-auto: create

server:
  port: 8443
  ssl:
    key-store: classpath:certs/local-keystore.p12
    key-store-password: dummypassword
    keyStoreType: PKCS12
    key-alias: tomcat
