spring:
  datasource:
    url: jdbc:mysql://localhost:13457?useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw&autoReconnect=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(PzqdJrsbvXzfvQ1f54zqxKwvB50lGNKi)
    password: ENC(2kL6hc5UhDpF9DdV+0Q9i1RBFVntbtVL6wPb403x2oE=)

  jpa:
    hibernate.ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5Dialect

server:
  port: 9876
  ssl:
    key-store: /home/pi/server/certs/keystore.p12
    key-store-password: ENC(h/DOzvvwNTGLp1JxCMRuLI+K/Cv6PMPZAQnIqFHSJOw=)
    keyStoreType: PKCS12
    key-alias: tomcat
